---
abstract: 'Create files and directories on disk'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  Directory::Scratch: 0
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Directory-Deploy
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan::Share: 0
  Moose: 0
  MooseX::AttributeHelpers: 0
  Path::Abstract: 0
  Path::Class: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/Directory-Deploy/tree/master
version: 0.002
